#!/usr/bin/env python3
"""
POC: instances/device.yaml → ttl-poc/device.abox.ttl

Fact layer 변환기 (수직 슬라이스 = device 도메인).
device fact yaml을 OWL ABox(NamedIndividual + data properties)로 직역한다.
semantic.classes.ttl(defined classes)과 같은 네임스페이스를 공유해야
reason(HermiT)이 device를 semantic class로 분류할 수 있다.

사용: python build_abox.py   (이 스크립트 디렉토리 기준 상대경로)
"""
import sys
from pathlib import Path
import yaml

NS = "https://agent-setup.local/ontology/asetup#"
ROOT = Path(__file__).resolve().parent.parent          # repo root
SRC = ROOT / "instances" / "device.yaml"
OUT = Path(__file__).resolve().parent / "owl" / "device.abox.ttl"

# semantic label derivation이 참조하는 fact 필드만 ABox로 투영 (POC 슬라이스).
# 누락 필드(price_usd, deployment_class)는 device.yaml에 없어 제외 — 발견사항으로 기록.
STR_FIELDS = ["type", "portability", "tier", "gpu_component"]
INT_FIELDS = ["memory_gb", "gpu_vram_gb"]
BOOL_FIELDS = ["always_on"]


def lit_str(v):
    return '"' + str(v).replace('"', '\\"') + '"'


def main():
    data = yaml.safe_load(SRC.read_text())
    devices = data["devices"]

    lines = [
        "# device.abox.ttl — GENERATED by ttl-poc/build_abox.py (do not edit by hand)",
        f"# source: instances/device.yaml (version {data.get('version')})",
        "",
        "@prefix :    <%s> ." % NS,
        "@prefix owl: <http://www.w3.org/2002/07/owl#> .",
        "@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .",
        "",
        "<https://agent-setup.local/ontology/asetup> a owl:Ontology .",
        "",
    ]

    count = 0
    for d in devices:
        did = d["id"]
        triples = [f":{did} a owl:NamedIndividual, :Device"]
        for f in STR_FIELDS:
            if d.get(f) is not None:
                triples.append(f"    :{f} {lit_str(d[f])}")
        for f in INT_FIELDS:
            if d.get(f) is not None:
                triples.append(f"    :{f} {int(d[f])}")
        for f in BOOL_FIELDS:
            if d.get(f) is not None:
                triples.append(f"    :{f} {str(bool(d[f])).lower()}")
        lines.append(" ;\n".join(triples) + " .")
        lines.append("")
        count += 1

    OUT.write_text("\n".join(lines))
    print(f"[+] {count} device individuals → {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
